-- =====================================================================
-- FinMind - Esquema inicial
-- Proyecto ADSO - SENA Centro Tecnologico de Manufactura Avanzada (CTMA)
-- Ficha 3114227
-- Motor: PostgreSQL 16 (Neon)  /  Codificacion: UTF-8 nativa
-- Zona horaria de la aplicacion: America/Bogota
--
-- Esta migracion nunca fue aplicada a ninguna base, por lo que se reescribio
-- en sitio al migrar de MySQL a PostgreSQL. Una vez aplicada, no se edita:
-- las correcciones entran como V2, V3, etc.
-- =====================================================================

-- ------------------------------------------------------------------ roles
CREATE TABLE roles (
    id          SMALLINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(30)   NOT NULL,
    descripcion VARCHAR(150),
    CONSTRAINT uk_roles_nombre UNIQUE (nombre)
);

INSERT INTO roles (nombre, descripcion) VALUES
    ('ROLE_USUARIO', 'Usuario final: gestiona unicamente sus propios datos financieros'),
    ('ROLE_ADMIN',   'Administrador: gestion de plataforma. NO accede a datos financieros de usuarios (RF-26)');

-- --------------------------------------------------------------- usuarios
-- fecha_actualizacion se mantiene desde Java con @PreUpdate.
-- PostgreSQL no tiene ON UPDATE CURRENT_TIMESTAMP como MySQL; hacerlo con un
-- trigger seria mas codigo que sostener por la misma funcionalidad.
CREATE TABLE usuarios (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(80)   NOT NULL,
    apellido            VARCHAR(80)   NOT NULL,
    correo              VARCHAR(120)  NOT NULL,
    contrasena_hash     VARCHAR(100)  NOT NULL,
    rol_id              SMALLINT      NOT NULL,
    activo              BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso       TIMESTAMP,
    CONSTRAINT uk_usuarios_correo UNIQUE (correo),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES roles (id)
);

CREATE INDEX idx_usuarios_rol ON usuarios (rol_id);

-- El correo se normaliza a minusculas en AuthService antes de guardar y de
-- buscar. PostgreSQL distingue mayusculas al comparar texto, a diferencia de
-- MySQL; sin esa normalizacion se podrian registrar dos cuentas con el mismo
-- correo escrito distinto.
COMMENT ON COLUMN usuarios.correo IS 'Siempre en minusculas, normalizado por la aplicacion';

-- ---------------------------------------------------------------- cuentas
CREATE TABLE cuentas (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT        NOT NULL,
    nombre         VARCHAR(80)   NOT NULL,
    tipo           VARCHAR(20)   NOT NULL,
    saldo_inicial  NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    moneda         CHAR(3)       NOT NULL DEFAULT 'COP',
    activa         BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cuentas_usuario_nombre UNIQUE (usuario_id, nombre),
    CONSTRAINT fk_cuentas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_cuentas_tipo CHECK (tipo IN
        ('EFECTIVO','AHORROS','CORRIENTE','TARJETA_CREDITO','BILLETERA_DIGITAL','OTRO'))
);

CREATE INDEX idx_cuentas_usuario ON cuentas (usuario_id);

-- ------------------------------------------------------------- categorias
CREATE TABLE categorias (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    nombre     VARCHAR(60) NOT NULL,
    tipo       VARCHAR(10) NOT NULL,
    icono      VARCHAR(40),
    color_hex  CHAR(7),
    activa     BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_categorias_usuario_nombre_tipo UNIQUE (usuario_id, nombre, tipo),
    CONSTRAINT fk_categorias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_categorias_tipo CHECK (tipo IN ('INGRESO','GASTO'))
);

COMMENT ON COLUMN categorias.usuario_id IS 'NULL = categoria del sistema, visible para todos';

CREATE INDEX idx_categorias_usuario ON categorias (usuario_id);

-- Indice parcial: garantiza que no se dupliquen las categorias del sistema.
-- En una restriccion UNIQUE los valores NULL se consideran distintos entre si,
-- asi que uk_categorias_usuario_nombre_tipo no protege las filas con
-- usuario_id NULL. Los indices parciales no existen en MySQL.
CREATE UNIQUE INDEX uk_categorias_sistema
    ON categorias (nombre, tipo) WHERE usuario_id IS NULL;

-- ----------------------------------------------------------- transacciones
CREATE TABLE transacciones (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT        NOT NULL,
    cuenta_id      BIGINT        NOT NULL,
    categoria_id   BIGINT        NOT NULL,
    tipo           VARCHAR(10)   NOT NULL,
    monto          NUMERIC(15,2) NOT NULL,
    fecha          DATE          NOT NULL,
    descripcion    VARCHAR(255),
    fecha_registro TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transacciones_usuario   FOREIGN KEY (usuario_id)   REFERENCES usuarios (id)   ON DELETE CASCADE,
    CONSTRAINT fk_transacciones_cuenta    FOREIGN KEY (cuenta_id)    REFERENCES cuentas (id)    ON DELETE CASCADE,
    CONSTRAINT fk_transacciones_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT ck_transacciones_monto CHECK (monto > 0),
    CONSTRAINT ck_transacciones_tipo  CHECK (tipo IN ('INGRESO','GASTO'))
);

-- Consulta mas frecuente de la aplicacion: los movimientos de un usuario en
-- un rango de fechas. De ahi el indice compuesto en ese orden.
CREATE INDEX idx_transacciones_usuario_fecha ON transacciones (usuario_id, fecha DESC);
CREATE INDEX idx_transacciones_cuenta        ON transacciones (cuenta_id);
CREATE INDEX idx_transacciones_categoria     ON transacciones (categoria_id);

-- ----------------------------------------------------------- presupuestos
CREATE TABLE presupuestos (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT        NOT NULL,
    categoria_id BIGINT        NOT NULL,
    monto_limite NUMERIC(15,2) NOT NULL,
    periodo      VARCHAR(10)   NOT NULL DEFAULT 'MENSUAL',
    anio         SMALLINT      NOT NULL,
    mes          SMALLINT      NOT NULL,
    activo       BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_presupuestos_periodo UNIQUE (usuario_id, categoria_id, anio, mes),
    CONSTRAINT fk_presupuestos_usuario   FOREIGN KEY (usuario_id)   REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_presupuestos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT ck_presupuestos_monto   CHECK (monto_limite > 0),
    CONSTRAINT ck_presupuestos_mes     CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_presupuestos_anio    CHECK (anio BETWEEN 2000 AND 2100),
    CONSTRAINT ck_presupuestos_periodo CHECK (periodo IN ('MENSUAL','QUINCENAL','SEMANAL'))
);

CREATE INDEX idx_presupuestos_usuario ON presupuestos (usuario_id, anio, mes);

-- ----------------------------------------------------------- metas_ahorro
CREATE TABLE metas_ahorro (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT        NOT NULL,
    nombre         VARCHAR(80)   NOT NULL,
    monto_objetivo NUMERIC(15,2) NOT NULL,
    monto_actual   NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    fecha_limite   DATE,
    estado         VARCHAR(12)   NOT NULL DEFAULT 'EN_CURSO',
    fecha_creacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_metas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_metas_objetivo CHECK (monto_objetivo > 0),
    CONSTRAINT ck_metas_actual   CHECK (monto_actual >= 0),
    CONSTRAINT ck_metas_estado   CHECK (estado IN ('EN_CURSO','COMPLETADA','CANCELADA'))
);

CREATE INDEX idx_metas_usuario ON metas_ahorro (usuario_id);

-- -------------------------------------------------------- auditoria_admin
-- Sustenta RF-26: se registra la accion del administrador sin exponer datos
-- financieros del usuario.
CREATE TABLE auditoria_admin (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id   BIGINT       NOT NULL,
    accion     VARCHAR(60)  NOT NULL,
    entidad    VARCHAR(60)  NOT NULL,
    entidad_id BIGINT,
    detalle    VARCHAR(255),
    fecha      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auditoria_admin FOREIGN KEY (admin_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_auditoria_admin_fecha ON auditoria_admin (admin_id, fecha DESC);

-- ------------------------------------------- categorias del sistema (semilla)
-- Datos de referencia, ficticios y no personales (DAT-04).
INSERT INTO categorias (usuario_id, nombre, tipo, icono, color_hex) VALUES
    (NULL, 'Salario',         'INGRESO', 'wallet',   '#15803D'),
    (NULL, 'Otros ingresos',  'INGRESO', 'plus',     '#0E8368'),
    (NULL, 'Alimentacion',    'GASTO',   'utensils', '#B45309'),
    (NULL, 'Transporte',      'GASTO',   'bus',      '#0B6B57'),
    (NULL, 'Vivienda',        'GASTO',   'home',     '#0A5647'),
    (NULL, 'Servicios',       'GASTO',   'bolt',     '#374151'),
    (NULL, 'Salud',           'GASTO',   'heart',    '#B91C1C'),
    (NULL, 'Educacion',       'GASTO',   'book',     '#6B7280'),
    (NULL, 'Entretenimiento', 'GASTO',   'film',     '#0E8368'),
    (NULL, 'Otros gastos',    'GASTO',   'dots',     '#D1D5DB');
