-- =====================================================================
-- FinMind - V2: verificacion del correo del usuario
-- Cambio registrado como CHG-05 en el DOC-02
-- Requisitos: RF-025 a RF-028 / Reglas: RN-011, RN-012, RN-014
-- =====================================================================

-- ------------------------------------------------- usuarios: identidad
-- Un usuario que entra con Google no define contrasena en FinMind: la
-- columna pasa a admitir nulo. Generar una contrasena que el usuario no
-- conoce crearia una credencial que nadie puede rotar ni revocar.
ALTER TABLE usuarios ALTER COLUMN contrasena_hash DROP NOT NULL;

ALTER TABLE usuarios
    ADD COLUMN correo_verificado BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN proveedor         VARCHAR(10) NOT NULL DEFAULT 'LOCAL',
    ADD COLUMN proveedor_id      VARCHAR(120);

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios_proveedor CHECK (proveedor IN ('LOCAL','GOOGLE'));

-- Coherencia entre origen de la identidad y credencial: quien se registra
-- en la aplicacion tiene contrasena; quien entra con Google, no.
ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios_credencial CHECK (
        (proveedor = 'LOCAL'  AND contrasena_hash IS NOT NULL) OR
        (proveedor = 'GOOGLE' AND contrasena_hash IS NULL)
    );

COMMENT ON COLUMN usuarios.proveedor_id IS
    'Identificador estable del usuario en Google. Nulo en cuentas locales';

COMMENT ON COLUMN usuarios.correo_verificado IS
    'RN-011: una cuenta sin verificar no puede iniciar sesion';

-- Los usuarios que ya existian se marcan como verificados: se registraron
-- antes de que la regla existiera y no seria correcto dejarlos sin acceso.
UPDATE usuarios SET correo_verificado = TRUE;

-- Localiza cuentas sin verificar para depuracion periodica
CREATE INDEX idx_usuarios_sin_verificar
    ON usuarios (correo_verificado) WHERE correo_verificado = FALSE;

-- Un mismo usuario de Google no puede quedar duplicado
CREATE UNIQUE INDEX uk_usuarios_proveedor_id
    ON usuarios (proveedor, proveedor_id) WHERE proveedor_id IS NOT NULL;

-- ------------------------------------------- codigos de verificacion
-- Una sola tabla para los dos flujos: verificacion del correo y
-- recuperacion de contrasena. Tienen la misma estructura y las mismas
-- reglas de vigencia, y los distingue la columna tipo.
CREATE TABLE codigos_verificacion (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT      NOT NULL,
    codigo      CHAR(6)     NOT NULL,
    tipo        VARCHAR(12) NOT NULL,
    intentos    SMALLINT    NOT NULL DEFAULT 0,
    creado_en   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_en   TIMESTAMP   NOT NULL,
    usado_en    TIMESTAMP,
    CONSTRAINT fk_codigos_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_codigos_tipo     CHECK (tipo IN ('VERIFICACION','RECUPERACION')),
    CONSTRAINT ck_codigos_formato  CHECK (codigo ~ '^[0-9]{6}$'),
    CONSTRAINT ck_codigos_intentos CHECK (intentos BETWEEN 0 AND 5),
    CONSTRAINT ck_codigos_vigencia CHECK (expira_en > creado_en)
);

-- Busqueda del codigo vigente de un usuario para un flujo determinado
CREATE INDEX idx_codigos_usuario_tipo
    ON codigos_verificacion (usuario_id, tipo, expira_en DESC);

-- Un solo codigo sin usar por usuario y tipo (RN-012): emitir uno nuevo
-- obliga a invalidar el anterior, lo que corta el abuso del reenvio.
CREATE UNIQUE INDEX uk_codigo_vigente
    ON codigos_verificacion (usuario_id, tipo) WHERE usado_en IS NULL;

COMMENT ON TABLE codigos_verificacion IS
    'Codigos de un solo uso con vigencia de 15 minutos (RNF-013)';
COMMENT ON COLUMN codigos_verificacion.intentos IS
    'Intentos fallidos. Al llegar a 5 el codigo queda inutilizable (DT-06)';
