-- =============================================================================
-- V3: Obligaciones financieras (RF-035 a RF-039, CR-006)
--
-- Por que una tabla aparte y no un tipo mas de cuenta:
-- una cuenta responde "cuanto tengo". Una obligacion responde "cuanto debo,
-- a quien, a que tasa y cuando vence la proxima cuota". Meterlas en la misma
-- tabla obligaria a dejar la mitad de las columnas vacias en cada fila y a
-- recordar en cada consulta que el signo se invierte segun el tipo.
-- =============================================================================

CREATE TABLE obligaciones (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT        NOT NULL,
    nombre             VARCHAR(80)   NOT NULL,
    acreedor           VARCHAR(80)   NOT NULL,
    tipo               VARCHAR(22)   NOT NULL,
    monto_original     NUMERIC(15,2) NOT NULL,
    saldo_pendiente    NUMERIC(15,2) NOT NULL,
    -- Porcentaje anual. 24.5000 significa 24.5% efectivo anual.
    -- Cuatro decimales porque las tasas se pactan con esa precision.
    tasa_anual         NUMERIC(7,4)  NOT NULL DEFAULT 0,
    cuota_mensual      NUMERIC(15,2) NOT NULL,
    dia_pago           SMALLINT      NOT NULL,
    fecha_inicio       DATE          NOT NULL,
    estado             VARCHAR(10)   NOT NULL DEFAULT 'ACTIVA',
    fecha_creacion     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_obligaciones_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uk_obligaciones_usuario_nombre UNIQUE (usuario_id, nombre),
    CONSTRAINT ck_obligaciones_tipo CHECK (tipo IN
        ('TARJETA_CREDITO','PRESTAMO_BANCARIO','PRESTAMO_PERSONAL','CREDITO_HIPOTECARIO',
         'CREDITO_VEHICULO','OTRO')),
    CONSTRAINT ck_obligaciones_estado CHECK (estado IN ('ACTIVA','PAGADA','CANCELADA')),
    CONSTRAINT ck_obligaciones_monto  CHECK (monto_original > 0),
    CONSTRAINT ck_obligaciones_cuota  CHECK (cuota_mensual > 0),
    -- El saldo nunca puede quedar negativo ni superar lo que se presto.
    CONSTRAINT ck_obligaciones_saldo  CHECK (saldo_pendiente >= 0
                                         AND saldo_pendiente <= monto_original),
    -- Tasa entre 0% y 200%: cero admite deudas sin interes (una a un familiar),
    -- y el techo atrapa el error de escribir 2400 en vez de 24.
    CONSTRAINT ck_obligaciones_tasa   CHECK (tasa_anual >= 0 AND tasa_anual <= 200),
    -- Hasta 28 para que exista en todos los meses, incluido febrero.
    CONSTRAINT ck_obligaciones_dia    CHECK (dia_pago BETWEEN 1 AND 28)
);

CREATE INDEX idx_obligaciones_usuario ON obligaciones (usuario_id, estado);
-- Para el aviso de cuotas proximas (RF-039) sobre las que siguen vivas.
CREATE INDEX idx_obligaciones_dia_pago ON obligaciones (dia_pago) WHERE estado = 'ACTIVA';


CREATE TABLE pagos_obligacion (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obligacion_id   BIGINT        NOT NULL,
    monto           NUMERIC(15,2) NOT NULL,
    -- RN-018: cada pago se guarda ya descompuesto. Si solo guardaramos el total,
    -- reconstruir cuanto fue interes exigiria recalcular toda la historia con las
    -- tasas vigentes en cada fecha, y el resultado dejaria de ser auditable.
    interes         NUMERIC(15,2) NOT NULL,
    abono_capital   NUMERIC(15,2) NOT NULL,
    saldo_resultante NUMERIC(15,2) NOT NULL,
    fecha           DATE          NOT NULL,
    descripcion     VARCHAR(255),
    fecha_registro  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pagos_obligacion FOREIGN KEY (obligacion_id)
        REFERENCES obligaciones (id) ON DELETE CASCADE,
    CONSTRAINT ck_pagos_monto     CHECK (monto > 0),
    CONSTRAINT ck_pagos_interes   CHECK (interes >= 0),
    -- RN-019: si el pago no cubre el interes, el abono a capital es cero.
    -- Nunca negativo: eso significaria que la deuda crecio dentro del pago.
    CONSTRAINT ck_pagos_capital   CHECK (abono_capital >= 0),
    CONSTRAINT ck_pagos_cuadre    CHECK (interes + abono_capital = monto),
    CONSTRAINT ck_pagos_saldo     CHECK (saldo_resultante >= 0)
);

CREATE INDEX idx_pagos_obligacion_fecha ON pagos_obligacion (obligacion_id, fecha DESC);
