-- =============================================================================
-- V9: gastos fijos (RF-046, RN-025, CR-012)
--
-- POR QUE HACE FALTA
-- La aplicacion sabe en que se gasto el dinero, pero no que compromisos vienen.
-- Para poder avisar "no te va a alcanzar para el arriendo" hay que saber que el
-- arriendo es un compromiso mensual de cierto monto. Hoy el arriendo es solo
-- una categoria de gastos pasados: la aplicacion no tiene forma de anticipar
-- nada, solo de contar lo que ya ocurrio.
--
-- Esta tabla es la base del modulo de alertas (V10 en adelante no hace falta:
-- las alertas se calculan, no se guardan).
--
-- QUE NO ES
-- No es un movimiento. Un gasto fijo es la INTENCION de un pago que se repite;
-- el pago real se sigue registrando como transaccion cuando ocurre. Mezclarlos
-- haria que el gasto se contara dos veces en el balance.
-- =============================================================================

CREATE TABLE gastos_fijos (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT        NOT NULL,
    categoria_id BIGINT        NOT NULL,
    nombre       VARCHAR(80)   NOT NULL,
    monto        NUMERIC(15,2) NOT NULL,
    periodicidad VARCHAR(10)   NOT NULL,
    -- Dia del mes en que se paga. Hasta 28 para que exista en febrero, igual
    -- que en las obligaciones.
    dia_pago     SMALLINT      NOT NULL,
    activo       BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fijos_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_fijos_categoria FOREIGN KEY (categoria_id)
        REFERENCES categorias (id),
    CONSTRAINT uk_fijos_usuario_nombre UNIQUE (usuario_id, nombre),
    CONSTRAINT ck_fijos_monto CHECK (monto > 0),
    CONSTRAINT ck_fijos_periodicidad CHECK (periodicidad IN ('MENSUAL','QUINCENAL','SEMANAL')),
    CONSTRAINT ck_fijos_dia CHECK (dia_pago BETWEEN 1 AND 28)
);

CREATE INDEX idx_fijos_usuario ON gastos_fijos (usuario_id, activo);

COMMENT ON TABLE gastos_fijos IS
    'Compromisos que se repiten: arriendo, servicios, suscripciones. Base del '
    'modulo de alertas. No son movimientos: el pago real se registra aparte';
